### PR TITLE
fix: Initialized OrderedDict to fix documentation function

### LINKED ISSUE #834: Uninitialized OrderedDict in hug.interface.Local.documentation()
Unable to call `.documentation()` on a `hug.local()` interface because the `doc` `OrderedDict` is not initialized.
```

~/.pyenv/versions/3.8.0/lib/python3.8/site-packages/hug/interface.py in documentation(self, add_to)
    316                 for requirement in self.requires
    317             ]
--> 318         doc["outputs"] = OrderedDict()
    319         doc["outputs"]["format"] = _doc(self.outputs)
    320         doc["outputs"]["content_type"] = self.outputs.content_type

TypeError: 'type' object does not support item assignment
```

```
306         def documentation(self, add_to=None):
307             """Produces general documentation for the interface"""
308             doc = OrderedDict if add_to is None else add_to
309
310             usage = self.interface.spec.__doc__
311             if usage:
312                 doc["usage"] = usage
313             if getattr(self, "requires", None):
314                 doc["requires"] = [
315                     getattr(requirement, "__doc__", requirement.__name__)
316                     for requirement in self.requires
317                 ]
318  ->         doc["outputs"] = OrderedDict()
```

### PR DESCRIPTION
**Pull request by mrsaicharan1**
Fixes #834 

**Description**:
- Initialized Ordered Dict to fix documentation function

### CODE REVIEW

**Comment by mrsaicharan1** [comment]
Travis fails with this. Is there a problem with `black` on Travis?

**Comment by mrsaicharan1** [comment]
Travis fails with this. Is there a problem with `black` on Travis?
```
ERROR: InvocationError for command /home/travis/build/hugapi/hug/.tox/py37-black/bin/black --check --verbose -l 100 hug (exited with code 1)
```

**Comment by mrsaicharan1** [comment]
Reformatted the file using black as well.

**Comment by mrsaicharan1** [comment]
@defrank @jay-tyler Would appreciate it if you could review this. Thanks!

**Comment by timothycrosley** [comment]
@mrsaicharan1 Thanks for making this fix! Travis is still failing, it looks like the wrong line length was used when running blac, should be `black -l 100 hug`

**Comment by mrsaicharan1** [comment]
@timothycrosley Oh right! I'm relatively new to black. Thanks for the heads up. Updating ASAP!

**Comment by mrsaicharan1** [comment]
@timothycrosley I hope this is GTG now!

**Comment by timothycrosley** [comment]
This looks great! Thanks so much @mrsaicharan1!

**Pull request merged**
